# Generated by Django 5.2.8 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaintenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False, verbose_name="メンテナンス中")),
                ("message", models.TextField(blank=True, default="", help_text="メンテナンス画面に表示する追加メッセージ（任意）", verbose_name="メッセージ")),
                ("scheduled_end", models.DateTimeField(blank=True, help_text="メンテナンス終了予定（任意）", null=True, verbose_name="終了予定")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "メンテナンス設定",
                "verbose_name_plural": "メンテナンス設定",
                "db_table": "site_maintenance",
            },
        ),
    ]


