# Generated by Django 5.2.8 on 2025-12-18

from django.db import migrations


def fix_sequence(apps, schema_editor):
    """
    PostgreSQL の採番シーケンスが pk=1 固定作成等でズレた場合に備えて補正する。
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    # site_maintenance.id のシーケンスを MAX(id) に合わせる
    schema_editor.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('site_maintenance', 'id'),
            COALESCE((SELECT MAX(id) FROM site_maintenance), 1),
            true
        );
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_site_maintenance"),
    ]

    operations = [
        migrations.RunPython(fix_sequence, reverse_code=migrations.RunPython.noop),
    ]


