version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    restart: unless-stopped
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/toybox
      - MONGODB_DB=toybox
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    volumes:
      - ./backend/public/uploads:/app/public/uploads:ro
  worker:
    build: ./backend
    command: node dist/src/workers/notificationWorker.js
    environment:
      - MONGODB_URI=mongodb://mongo:27017/toybox
      - MONGODB_DB=toybox
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  mongo-data:
