# Generated by Django 5.2.8 on 2025-11-12 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JackpotWin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("won_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("pinned_until", models.DateTimeField(blank=True, null=True)),
                (
                    "old_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "jackpot_wins",
            },
        ),
        migrations.CreateModel(
            name="LotteryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.008"), max_digits=5
                    ),
                ),
                (
                    "per_submit_increment",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.002"), max_digits=5
                    ),
                ),
                (
                    "max_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.05"), max_digits=5
                    ),
                ),
                ("daily_cap", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lottery_rules",
            },
        ),
    ]
