# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lottery", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jackpotwin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jackpot_wins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="jackpotwin",
            index=models.Index(fields=["won_at"], name="jackpot_win_won_at_5a6a38_idx"),
        ),
        migrations.AddIndex(
            model_name="jackpotwin",
            index=models.Index(
                fields=["user", "won_at"], name="jackpot_win_user_id_dd09fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jackpotwin",
            index=models.Index(fields=["old_id"], name="jackpot_win_old_id_30c1a8_idx"),
        ),
    ]
