# Generated by Django 5.2.8 on 2025-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("submit_medal", "Submit Medal")], max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reactions",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("caption", models.TextField(blank=True, max_length=1000)),
                ("comment_enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("delete_reason", models.TextField(blank=True, null=True)),
                ("aim", models.CharField(blank=True, max_length=100)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("frame_type", models.CharField(blank=True, max_length=50)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("video_url", models.URLField(blank=True, max_length=500, null=True)),
                ("game_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "jp_result",
                    models.CharField(blank=True, default="none", max_length=10),
                ),
                ("likes_count", models.IntegerField(default=0)),
                (
                    "old_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
