# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="submissions.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["-created_at"], name="submissions_created_80fb8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["deleted_at"], name="submissions_deleted_8ecb47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["author", "-created_at"], name="submissions_author__bc0ef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["old_id"], name="submissions_old_id_0bc3c4_idx"),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["submission", "type"], name="reactions_submiss_75ddcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["user", "created_at"], name="reactions_user_id_43f59d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "submission", "type")},
        ),
    ]
