# Generated by Django 5.2.8 on 2025-12-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'リアクション', 'verbose_name_plural': 'リアクション'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AddField(
            model_name='submission',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='ハッシュタグ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='submissions.submission', verbose_name='投稿'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('submit_medal', '投稿メダル')], max_length=50, verbose_name='リアクションタイプ'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='caption',
            field=models.TextField(blank=True, max_length=140, verbose_name='キャプション'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comment_enabled',
            field=models.BooleanField(default=True, verbose_name='コメント有効'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='delete_reason',
            field=models.TextField(blank=True, null=True, verbose_name='削除理由'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PUBLIC', '公開'), ('PRIVATE', '非公開'), ('FLAGGED', 'フラグ付き')], default='PUBLIC', max_length=20, verbose_name='ステータス'),
        ),
    ]
