# Generated by Django 5.2.8 on 2025-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("share_channel", models.CharField(max_length=100)),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "old_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "discord_shares",
            },
        ),
    ]
