# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sharing", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordshare",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discord_shares",
                to="submissions.submission",
            ),
        ),
    ]
