# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sharing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discordshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discord_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="discordshare",
            index=models.Index(
                fields=["shared_at"], name="discord_sha_shared__d5a5a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordshare",
            index=models.Index(
                fields=["user", "shared_at"], name="discord_sha_user_id_224d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordshare",
            index=models.Index(fields=["old_id"], name="discord_sha_old_id_bb0cdf_idx"),
        ),
    ]
