# Generated by Django 5.2.8 on 2025-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("WARN", "Warn"),
                            ("SUSPEND", "Suspend"),
                            ("UNSUSPEND", "Unsuspend"),
                            ("BAN", "Ban"),
                            ("UNBAN", "Unban"),
                            ("DELETE", "Delete"),
                            ("RESTORE", "Restore"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "admin_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
