# Generated by Django 5.2.8 on 2025-11-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WARN", "Warn"),
                    ("SUSPEND", "Suspend"),
                    ("UNSUSPEND", "Unsuspend"),
                    ("BAN", "Ban"),
                    ("UNBAN", "Unban"),
                    ("DELETE", "Delete"),
                    ("RESTORE", "Restore"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("EDIT_PROFILE", "Edit Profile"),
                    ("IMPORT", "Import"),
                ],
                max_length=50,
            ),
        ),
    ]
