# Generated by Django 5.2.8 on 2025-11-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"verbose_name": "カード", "verbose_name_plural": "カード"},
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["name"],
                "verbose_name": "称号",
                "verbose_name_plural": "称号",
            },
        ),
        migrations.AddField(
            model_name="card",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="カードの画像をアップロードします。",
                null=True,
                upload_to="cards/",
                verbose_name="画像",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="code",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="コード"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="card",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="外部URLから画像を指定する場合に使用します。",
                max_length=500,
                null=True,
                verbose_name="画像URL",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=100, verbose_name="カード名"),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "コモン"),
                    ("rare", "レア"),
                    ("seasonal", "シーズナル"),
                    ("special", "スペシャル"),
                ],
                default="common",
                max_length=20,
                verbose_name="レアリティ",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="色"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="title",
            name="duration_days",
            field=models.IntegerField(default=7, verbose_name="有効期間（日）"),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="称号名"),
        ),
        migrations.AlterField(
            model_name="title",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
