# Generated by Django 5.2.8 on 2025-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0002_alter_card_options_alter_title_options_card_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="称号のバナー画像（321×115px推奨）をアップロードします。",
                null=True,
                upload_to="titles/",
                verbose_name="バナー画像",
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="外部URLから画像を指定する場合に使用します。",
                max_length=500,
                null=True,
                verbose_name="画像URL",
            ),
        ),
    ]
