# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(max_length=128)),
                ("display_id", models.CharField(db_index=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("OFFICE", "Office"),
                            ("AYATORI", "Ayatori"),
                            ("ADMIN", "Admin"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                ("warning_count", models.IntegerField(default=0)),
                ("warning_notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "old_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtained_at", models.DateTimeField(auto_now_add=True)),
                ("old_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cards",
                        to="gamification.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_cards",
            },
        ),
        migrations.CreateModel(
            name="UserMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title_color", models.CharField(blank=True, max_length=50, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("header_url", models.URLField(blank=True, max_length=500)),
                ("lottery_bonus_count", models.IntegerField(default=0)),
                (
                    "old_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_meta",
            },
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_registrations",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["display_id"], name="users_display_a5c640_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_suspended"], name="users_is_susp_5a4b6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["old_id"], name="users_old_id_572f1c_idx"),
        ),
        migrations.AddIndex(
            model_name="usercard",
            index=models.Index(
                fields=["user", "obtained_at"], name="user_cards_user_id_e808f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercard",
            index=models.Index(fields=["old_id"], name="user_cards_old_id_3c159e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usercard",
            unique_together={("user", "card")},
        ),
        migrations.AddIndex(
            model_name="usermeta",
            index=models.Index(
                fields=["expires_at"], name="user_meta_expires_246fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermeta",
            index=models.Index(fields=["old_id"], name="user_meta_old_id_2524b2_idx"),
        ),
    ]
