# Generated by Django 5.2.8 on 2025-11-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
    ]
