# Generated by Django 5.2.8 on 2025-11-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
