# Generated by Django 5.2.8 on 2025-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usermeta_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="notifications",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
