# Generated by Django 5.2.8 on 2025-11-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usermeta_notifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "ユーザー", "verbose_name_plural": "ユーザー"},
        ),
        migrations.AlterModelOptions(
            name="usercard",
            options={
                "verbose_name": "ユーザーカード",
                "verbose_name_plural": "ユーザーカード",
            },
        ),
        migrations.AlterModelOptions(
            name="usermeta",
            options={
                "verbose_name": "ユーザーメタ情報",
                "verbose_name_plural": "ユーザーメタ情報",
            },
        ),
        migrations.AlterModelOptions(
            name="userregistration",
            options={
                "verbose_name": "ユーザー登録情報",
                "verbose_name_plural": "ユーザー登録情報",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="penalty_message",
            field=models.TextField(
                blank=True,
                help_text="ユーザーに表示する警告・ペナルティメッセージ",
                null=True,
                verbose_name="ペナルティメッセージ",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="penalty_type",
            field=models.CharField(
                blank=True,
                help_text="WARNING: 警告, SUSPEND: アカウント停止, BAN: BAN（アカウント削除）",
                max_length=20,
                null=True,
                verbose_name="ペナルティタイプ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="アバターURL"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="BAN日時"),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_id",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="表示ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="メールアドレス",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="このユーザーがアクティブかどうか。無効にするとログインできません。",
                verbose_name="アクティブ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="このユーザーがDjango管理サイトにアクセスできるかどうか。",
                verbose_name="管理サイトアクセス権限",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="このユーザーがすべての権限を持つかどうか。",
                verbose_name="スーパーユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="アカウント停止"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="パスワード"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "一般ユーザー"),
                    ("OFFICE", "オフィス"),
                    ("AYATORI", "あやとり"),
                    ("ADMIN", "管理者"),
                ],
                default="USER",
                max_length=20,
                verbose_name="役割",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="warning_count",
            field=models.IntegerField(default=0, verbose_name="警告回数"),
        ),
        migrations.AlterField(
            model_name="user",
            name="warning_notes",
            field=models.TextField(blank=True, null=True, verbose_name="警告メモ"),
        ),
    ]
