# Generated by Django 5.2.8 on 2025-11-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_alter_usercard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("FREE_USER", "一般ユーザー"),
                    ("PAID_USER", "課金ユーザー"),
                    ("ADMIN", "管理者"),
                    ("SUPERUSER", "スーパーユーザー"),
                ],
                default="FREE_USER",
                max_length=20,
                verbose_name="役割",
            ),
        ),
    ]
