# Generated by Django 5.2.8 on 2025-12-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="初回起動時のオンボーディングが完了したかどうか",
                verbose_name="オンボーディング完了",
            ),
        ),
    ]
