# Generated by Django 5.2.8 on 2025-12-05 02:47

from django.db import migrations, models
import json


def convert_boolean_to_json(apps, schema_editor):
    """Convert boolean onboarding_completed to JSON format."""
    UserMeta = apps.get_model('users', 'UserMeta')
    db_alias = schema_editor.connection.alias
    
    for meta in UserMeta.objects.using(db_alias).all():
        # Get the raw boolean value from the database
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT onboarding_completed FROM user_meta WHERE id = %s",
                [meta.id]
            )
            row = cursor.fetchone()
            if row:
                bool_value = row[0]
                
                # Convert boolean to JSON
                if bool_value:
                    json_value = json.dumps({
                        'me': True,
                        'collection': True,
                        'profile': True,
                        'feed': True
                    })
                else:
                    json_value = json.dumps({
                        'me': False,
                        'collection': False,
                        'profile': False,
                        'feed': False
                    })
                
                # Update the field directly in the database
                cursor.execute(
                    "UPDATE user_meta SET onboarding_completed_temp = %s::jsonb WHERE id = %s",
                    [json_value, meta.id]
                )


def reverse_convert_json_to_boolean(apps, schema_editor):
    """Reverse conversion: convert JSON to boolean (all pages must be True for True)."""
    UserMeta = apps.get_model('users', 'UserMeta')
    db_alias = schema_editor.connection.alias
    
    for meta in UserMeta.objects.using(db_alias).all():
        # Get the raw JSON value from the database
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT onboarding_completed_temp FROM user_meta WHERE id = %s",
                [meta.id]
            )
            row = cursor.fetchone()
            if row:
                json_value = row[0]
                if json_value:
                    # Parse JSON and check if all pages are completed
                    if isinstance(json_value, str):
                        data = json.loads(json_value)
                    else:
                        data = json_value
                    
                    all_completed = all(
                        data.get(key, False)
                        for key in ['me', 'collection', 'profile', 'feed']
                    )
                    
                    # Update the field directly in the database
                    cursor.execute(
                        "UPDATE user_meta SET onboarding_completed = %s WHERE id = %s",
                        [all_completed, meta.id]
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usermeta_onboarding_completed"),
    ]

    operations = [
        # Step 1: Add temporary JSONField
        migrations.AddField(
            model_name="usermeta",
            name="onboarding_completed_temp",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                help_text='各ページごとのオンボーディング完了状態 {"me": false, "collection": false, "profile": false, "feed": false}',
                verbose_name="オンボーディング完了状態（一時）",
            ),
        ),
        # Step 2: Migrate data
        migrations.RunPython(convert_boolean_to_json, reverse_convert_json_to_boolean),
        # Step 3: Remove old field and rename new field
        migrations.RemoveField(
            model_name="usermeta",
            name="onboarding_completed",
        ),
        migrations.RenameField(
            model_name="usermeta",
            old_name="onboarding_completed_temp",
            new_name="onboarding_completed",
        ),
        # Step 4: Update field properties
        migrations.AlterField(
            model_name="usermeta",
            name="onboarding_completed",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='各ページごとのオンボーディング完了状態 {"me": false, "collection": false, "profile": false, "feed": false}',
                verbose_name="オンボーディング完了状態",
            ),
        ),
    ]
