# Generated by Django 5.2.8 on 2025-12-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0002_alter_card_options_alter_title_options_card_image_and_more",
        ),
        ("users", "0008_alter_usermeta_onboarding_completed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercard",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="usercard",
            index=models.Index(
                fields=["user", "card"], name="user_cards_user_id_3f9d5d_idx"
            ),
        ),
    ]
