# Generated by Django 5.2.8 on 2025-12-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_usercard_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="discord_access_token",
            field=models.TextField(
                blank=True,
                help_text="Discord OAuth2アクセストークン（暗号化推奨）",
                null=True,
                verbose_name="Discordアクセストークン",
            ),
        ),
        migrations.AddField(
            model_name="usermeta",
            name="discord_refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Discord OAuth2リフレッシュトークン（暗号化推奨）",
                null=True,
                verbose_name="Discordリフレッシュトークン",
            ),
        ),
        migrations.AddField(
            model_name="usermeta",
            name="discord_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Discordアクセストークンの有効期限",
                null=True,
                verbose_name="Discordトークン有効期限",
            ),
        ),
        migrations.AddField(
            model_name="usermeta",
            name="discord_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DiscordユーザーID",
                max_length=100,
                null=True,
                verbose_name="DiscordユーザーID",
            ),
        ),
        migrations.AddField(
            model_name="usermeta",
            name="discord_username",
            field=models.CharField(
                blank=True,
                help_text="Discordユーザー名（例: username#1234）",
                max_length=255,
                null=True,
                verbose_name="Discordユーザー名",
            ),
        ),
    ]
