# Generated by Django 5.2.8 on 2025-12-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_add_discord_oauth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="terms_agreed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="課金ユーザーが利用規約に同意した日時",
                null=True,
                verbose_name="利用規約同意日時",
            ),
        ),
    ]
