# Generated by Django 5.2.8 on 2025-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_terms_agreed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeta",
            name="header_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
