# Generated by Django 5.2.9 on 2025-12-16 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_usermeta_header_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSSOLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="例: studysphere",
                        max_length=50,
                        verbose_name="SSOプロバイダー",
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="StudySphereのユーザーIDなど",
                        max_length=255,
                        verbose_name="外部ユーザーID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SSO連携情報",
                "verbose_name_plural": "SSO連携情報",
                "db_table": "user_sso_links",
                "indexes": [
                    models.Index(
                        fields=["provider", "external_user_id"],
                        name="user_sso_li_provide_24299a_idx",
                    ),
                    models.Index(
                        fields=["user", "provider"],
                        name="user_sso_li_user_id_7311cf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="user_sso_li_created_cb430a_idx"
                    ),
                ],
                "unique_together": {("provider", "external_user_id")},
            },
        ),
    ]
