# Generated by Django 5.x on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_add_user_sso_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="studysphere_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
                verbose_name="StudySphereユーザーID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="studysphere_login_code",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="StudySphereログインコード",
            ),
        ),
    ]
